package com.aiagent.util;

import io.jsonwebtoken.Claims;
import io.jsonwebtoken.Jwts;
import io.jsonwebtoken.security.Keys;
import jakarta.annotation.PostConstruct;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.stereotype.Component;

import javax.crypto.SecretKey;
import java.util.Date;

/**
 * SEC-005 — JWT is currently generated by AuthService (on /auth/login and
 * /auth/google-login) but not enforced anywhere: there is no
 * JwtAuthenticationFilter, and the application authenticates exclusively
 * via Spring Security sessions (form login + Google OAuth2). This class
 * exists for that dormant/incomplete JWT path only and does not
 * participate in request authorization today.
 */
@Component
public class JwtTokenProvider {

          @Value("${jwt.secret:}")
          private String jwtSecret;

          @Value("${jwt.expiration:86400000}")
          private long jwtExpiration;

          @PostConstruct
          void validateSecret() {
                    if (jwtSecret == null || jwtSecret.isBlank()) {
                              throw new IllegalStateException(
                                        "jwt.secret is not configured. Set the JWT_SECRET environment variable "
                                                  + "(see .env.example) before starting the application — a predictable "
                                                  + "default secret is never used as a fallback.");
                    }
          }

          public String generateToken(String email, Long userId) {
                    Date now = new Date();
                    Date expiryDate = new Date(now.getTime() + jwtExpiration);

                    SecretKey key = Keys.hmacShaKeyFor(jwtSecret.getBytes());

                    return Jwts.builder()
                                        .subject(email)
                                        .claim("userId", userId)
                                        .issuedAt(now)
                                        .expiration(expiryDate)
                                        .signWith(key)
                                        .compact();
          }

          public String getEmailFromToken(String token) {
                    SecretKey key = Keys.hmacShaKeyFor(jwtSecret.getBytes());
                    Claims claims = Jwts.parser()
                                        .verifyWith(key)
                                        .build()
                                        .parseSignedClaims(token)
                                        .getPayload();
                    return claims.getSubject();
          }

          public Long getUserIdFromToken(String token) {
                    SecretKey key = Keys.hmacShaKeyFor(jwtSecret.getBytes());
                    Claims claims = Jwts.parser()
                                        .verifyWith(key)
                                        .build()
                                        .parseSignedClaims(token)
                                        .getPayload();
                    return claims.get("userId", Long.class);
          }

          public boolean validateToken(String token) {
                    try {
                              SecretKey key = Keys.hmacShaKeyFor(jwtSecret.getBytes());
                              Jwts.parser()
                                                  .verifyWith(key)
                                                  .build()
                                                  .parseSignedClaims(token);
                              return true;
                    } catch (Exception ex) {
                              return false;
                    }
          }
}
